name: Angular GitHub CI
on:
  push:
    branches:
      - main
      - dev

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/wikipedia-graph-frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Build
        run: |
          npm run build
      - name: Lint
        run: |
          npm run lint
